# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihdoKn-HWXsi_cK-N69H-FDZcqgkufSN
"""

!pip install mediapipe opencv-python

# Install dependencies (if not installed)
#!pip install mediapipe opencv-python

# Import required libraries
import cv2
import mediapipe as mp
from google.colab.patches import cv2_imshow  # Use cv2_imshow for Colab

# Initialize MediaPipe Pose
mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils

# Upload an image to Colab manually and use the filename here
image_path = "pose.jpg"  # Change this to the actual file name after uploading
image = cv2.imread(image_path)

# Convert BGR to RGB (MediaPipe expects RGB images)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Run Pose Estimation
with mp_pose.Pose(static_image_mode=True) as pose:
    results = pose.process(image_rgb)
    if results.pose_landmarks:
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

# ✅ Use cv2_imshow() instead of cv2.imshow()
cv2_imshow(image)

"""# New Section"""